/* prettier-ignore-start */
/**
 * This file is auto-generated by generator/router/generate-router-contract.ts
 * Do not edit this file manually.
 */

export const paths = {
  analytics: '/analytics',
  'create-org': '/organizations/create',
  employees: '/employees',
  groups: '/groups',
  home: '/',
  report: '/report',
  schedule: '/schedule',
  'sign-in': '/sign-in',
  'sign-up': '/sign-up',
  students: '/students',
} as const

export type RouteId = keyof typeof paths
export type PathsKeys = (typeof paths)[RouteId]
export type PathById<T extends RouteId> = (typeof paths)[T]
/* prettier-ignore-end */
