/* prettier-ignore-start */
/**
 * This file is auto-generated by scripts/generate-router-contract.ts
 * Do not edit this file manually.
 */

export const paths = {
  home: '/',
  analytics: '/analytics',
  schedule: '/schedule',
  employees: '/employees',
  students: '/students',
  groups: '/groups',
  report: '/report',
  'sign-up': '/sign-up',
  'sign-in': '/sign-in',
} as const

export type RouteId = keyof typeof paths
export type PathsKeys = (typeof paths)[RouteId]
export type PathById<T extends RouteId> = (typeof paths)[T]
/* prettier-ignore-end */
