# Generated by Django 5.2.6 on 2025-11-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('user', 'Пользователь'), ('student', 'Ученик'), ('teacher', 'Учитель')], default='user', max_length=20),
        ),
    ]
